apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd-cdc
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prod
    repoURL: https://github.com/preddykolan19/cicd-argo-tek.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true