---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-extra-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd-cdc
roleRef:
  kind: ClusterRole
  name: argocd-application-controller-role
  apiGroup: rbac.authorization.k8s.io
